version: 0.2
phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - bundle install
      - bundle exec middleman build --clean
  post_build:
    commands:
      - echo "Uploading build to S3"
      - aws s3 cp --recursive ./build s3://$S3_BUCKET_NAME/
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths /index.html
artifacts:
  files:
  base-directory:
cache:
  paths:
    - node_modules
